# Generated by Django 5.2.8 on 2026-05-31 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='🪑', max_length=50, verbose_name='Emoji belgisi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Rasm')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before/', verbose_name='Oldin (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio ishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('text', models.TextField(verbose_name='Fikr')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Rasm (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz fikri',
                'verbose_name_plural': 'Mijozlar fikrlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+998901234567', max_length=20, verbose_name='Telefon')),
                ('telegram', models.CharField(default='https://t.me/jadidmebel', max_length=100, verbose_name='Telegram link')),
                ('whatsapp', models.CharField(default='+998901234567', max_length=20, verbose_name='WhatsApp raqam')),
                ('address', models.CharField(default='Toshkent sh., Yunusobod tumani', max_length=300, verbose_name='Manzil')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram link')),
                ('about_text', models.TextField(default='Jadid Mebel — 2018-yildan beri Toshkentda sifatli mebel ishlab chiqarmoqda.', verbose_name='Biz haqimizda matni')),
                ('map_embed', models.TextField(blank=True, verbose_name='Google Maps iframe kodi')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('material', models.CharField(choices=[('yogoch', "Yog'och"), ('mdf', 'MDF'), ('metall', 'Metall'), ('shisha', 'Shisha'), ('kombinatsiya', 'Kombinatsiya')], default='yogoch', max_length=50, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Rang')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Narx (so'm)")),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', "Ko'rib chiqilmoqda"), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
